baseURL = "https://go-testdeep.zetta.rocks/"
languageCode = "en-us"
title = "go-testdeep"
theme = "hugo-theme-relearn"

enableGitInfo = true

PygmentsCodeFences = true
PygmentsStyle = "native"

ignoreLogs = ['warning-goldmark-raw-html', 'warning-partial-superfluous-prefix']

# For search functionality
[outputs]
home = ["html", "rss"]

[params]
disableLandingPageButton = true
disableInlineCopyToClipBoard = true
themeVariant = "green"
hideAuthorName = true

[minify.tdewolff.html]
keepWhitespace=true

[[menu.shortcuts]]
name = "<i class='fab fa-slideshare'></i>&nbsp;Presentation"
identifier = "prez"
url = "/prez"
weight = 5

[[menu.shortcuts]]
name = "<i class='fab fa-github'></i>&nbsp;Github repo"
identifier = "ds"
url = "https://github.com/maxatome/go-testdeep"
weight = 10

[[menu.shortcuts]]
name = "<i class='fas fa-book'></i>&nbsp;godoc"
identifier = "godoc"
url = "https://pkg.go.dev/github.com/maxatome/go-testdeep/td"
weight = 15

[[menu.shortcuts]]
name = "<i class='fas fa-book'></i>&nbsp;godoc API tester — tdhttp"
identifier = "godoc-tdhttp"
url = "https://pkg.go.dev/github.com/maxatome/go-testdeep/helpers/tdhttp"
weight = 20

[[menu.shortcuts]]
name = "<i class='fas fa-book'></i>&nbsp;godoc testing suite — tdsuite"
identifier = "godoc-tdsuite"
url = "https://pkg.go.dev/github.com/maxatome/go-testdeep/helpers/tdsuite"
weight = 25

[[menu.shortcuts]]
name = "<i class='fas fa-book'></i>&nbsp;godoc helpers utils — tdutil"
identifier = "godoc-tdutil"
url = "https://pkg.go.dev/github.com/maxatome/go-testdeep/helpers/tdutil"
weight = 30
